import 'package:flutter/material.dart';
import 'package:vail_app/core/constants/app_constants.dart';
import 'package:vail_app/core/theme/vail_theme.dart';

/// The mode that drives what content the card shows.
///
/// - [disclaimer] — AI accuracy notice only. Default state.
/// - [upgradeNudge] — free-tier user on a small model. Shows the nudge,
///   an upgrade CTA, and the disclaimer.
/// - [modelSuggestion] — pro-tier user on a sub-optimal model. Shows the
///   suggestion and the disclaimer, no paywall CTA.
enum InsightMode { disclaimer, upgradeNudge, modelSuggestion }

/// Resolves the correct [InsightMode] for a given model and plan tier.
///
/// Free tier:
///   vail-lite → upgradeNudge (nudge to VAIL.CORE free + VAIL.PRO paywall)
///   vail      → disclaimer   (VAIL.CORE is the best free model)
///
/// Pro tier:
///   vail-lite / vail → modelSuggestion (larger model available, no extra cost)
///   vail-pro / vail-max → disclaimer   (on best available model)
InsightMode resolveInsightMode(String model, bool isPro) {
  if (isPro) {
    return (model == 'vail-pro' || model == 'vail-max')
        ? InsightMode.disclaimer
        : InsightMode.modelSuggestion;
  }
  return model == 'vail-lite' ? InsightMode.upgradeNudge : InsightMode.disclaimer;
}

/// Dismissable card that appears below qualifying assistant responses.
///
/// Always shows the AI accuracy disclaimer. On top of that, [upgradeNudge]
/// and [modelSuggestion] modes add model-specific guidance.
///
/// Rendered by the chat view — do not construct directly outside of it.
class ResponseInsightCard extends StatelessWidget {
  final InsightMode mode;
  final String activeModel;
  final VoidCallback onDismiss;

  /// Only required for [InsightMode.upgradeNudge]. Called when the user taps
  /// "Upgrade to Pro". Ignored in other modes.
  final VoidCallback? onUpgrade;

  const ResponseInsightCard({
    required this.mode,
    required this.activeModel,
    required this.onDismiss,
    this.onUpgrade,
    super.key,
  });

  // ── Content helpers ────────────────────────────────────────────────────────

  /// Body copy for [InsightMode.upgradeNudge] (free-tier users).
  ///
  /// Accurate to the actual model tiers: VAIL.LITE = Gemma 4 E2B (speed),
  /// VAIL.CORE = Gemma 4 26B MoE (balanced), VAIL.PRO = Gemma 4 31B (reasoning).
  String get _nudgeText {
    if (activeModel == 'vail-lite') {
      return 'This response was generated by VAIL.LITE, optimised for speed. '
          'VAIL.CORE — available on your free plan — offers better reasoning and '
          'extended context. Upgrade to Pro for VAIL.PRO with advanced multi-step '
          'reasoning and priority routing.';
    }
    return 'Upgrade to Pro to access ${AppConstants.modelDisplayName(_suggestedModel)} '
        'for more capable responses on complex tasks.';
  }

  /// Body copy for [InsightMode.modelSuggestion] (pro-tier users).
  String get _suggestionText => switch (activeModel) {
        'vail-lite' =>
          'VAIL.LITE is optimised for speed. Switch to VAIL.CORE or VAIL.PRO '
              'in the model selector for a more thorough response on complex tasks.',
        'vail' =>
          'VAIL.CORE handled this response. VAIL.PRO offers deeper reasoning '
              'and extended context — consider switching for complex multi-step tasks.',
        _ =>
          'A larger model may yield more thorough results for this type of request.',
      };

  /// The next model up from the current active one.
  String get _suggestedModel => switch (activeModel) {
        'vail-lite' => 'vail',
        'vail' => 'vail-pro',
        _ => 'vail-pro',
      };

  // ── Visual helpers ─────────────────────────────────────────────────────────

  String get _title => switch (mode) {
        InsightMode.disclaimer => 'ACCURACY NOTICE',
        InsightMode.upgradeNudge => 'UPGRADE FOR BETTER RESULTS',
        InsightMode.modelSuggestion => 'IMPROVE YOUR RESULTS',
      };

  Color _titleColor(bool isUpgrade) =>
      isUpgrade ? const Color(0xFFE5C07B) : VailTheme.textSecondary;

  IconData get _icon => mode == InsightMode.disclaimer
      ? Icons.info_outline_rounded
      : Icons.auto_awesome_rounded;

  // ── Build ──────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final isUpgrade = mode == InsightMode.upgradeNudge;
    final titleColor = _titleColor(isUpgrade);

    return Padding(
      padding: const EdgeInsets.fromLTRB(
        VailTheme.lg, 0, VailTheme.lg, VailTheme.md,
      ),
      child: Container(
        decoration: BoxDecoration(
          color: VailTheme.surfaceContainerLow,
          border: Border.all(color: VailTheme.ghostBorder),
          borderRadius: BorderRadius.circular(VailTheme.radiusMd),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header row
            Padding(
              padding: const EdgeInsets.fromLTRB(
                VailTheme.md, VailTheme.md, VailTheme.md, 0,
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Icon(_icon, size: 13, color: titleColor),
                  const SizedBox(width: VailTheme.sm),
                  Expanded(
                    child: Text(
                      _title,
                      style: VailTheme.mono.copyWith(
                        color: titleColor,
                        fontSize: 9,
                        letterSpacing: 1.5,
                      ),
                    ),
                  ),
                  GestureDetector(
                    onTap: onDismiss,
                    behavior: HitTestBehavior.opaque,
                    child: const Padding(
                      padding: EdgeInsets.only(left: VailTheme.sm),
                      child: Icon(
                        Icons.close_rounded,
                        size: 14,
                        color: VailTheme.textMuted,
                      ),
                    ),
                  ),
                ],
              ),
            ),

            // Body
            Padding(
              padding: const EdgeInsets.fromLTRB(
                VailTheme.md, VailTheme.sm, VailTheme.md, VailTheme.md,
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Nudge / suggestion text (non-disclaimer modes only)
                  if (mode != InsightMode.disclaimer) ...[
                    Text(
                      mode == InsightMode.upgradeNudge
                          ? _nudgeText
                          : _suggestionText,
                      style: VailTheme.bodySmall.copyWith(
                        color: VailTheme.textSecondary,
                        height: 1.55,
                      ),
                    ),

                    // Upgrade CTA (free tier only)
                    if (isUpgrade) ...[
                      const SizedBox(height: VailTheme.md),
                      GestureDetector(
                        onTap: onUpgrade,
                        child: Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: VailTheme.md,
                            vertical: VailTheme.xs + 2,
                          ),
                          decoration: BoxDecoration(
                            color: const Color(0xFFE5C07B).withValues(alpha: 0.08),
                            border: Border.all(
                              color: const Color(0xFFE5C07B).withValues(alpha: 0.45),
                            ),
                            borderRadius:
                                BorderRadius.circular(VailTheme.radiusSm),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Text(
                                'UPGRADE TO PRO',
                                style: VailTheme.mono.copyWith(
                                  color: const Color(0xFFE5C07B),
                                  fontSize: 9,
                                  letterSpacing: 1.5,
                                ),
                              ),
                              const SizedBox(width: VailTheme.xs),
                              const Icon(
                                Icons.arrow_forward_rounded,
                                size: 11,
                                color: Color(0xFFE5C07B),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],

                    const SizedBox(height: VailTheme.md),
                    const Divider(height: 1, color: VailTheme.borderSubtle),
                    const SizedBox(height: VailTheme.sm),
                  ],

                  // Disclaimer — always present
                  Text(
                    'AI systems can make mistakes. Always verify important '
                    'information before applying it.',
                    style: VailTheme.mono.copyWith(
                      color: VailTheme.textMuted,
                      fontSize: 9,
                      letterSpacing: 0.4,
                      height: 1.65,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
